config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :clients, controllers: { registrations: 'clients/registrations', sessions: 'clients/sessions' }
  devise_for :employees, controllers: { registrations: 'employees/registrations', sessions: 'employees/sessions' }

  get 'services/:id/add_to_favorites', to: 'client_profiles#add_to_favorites', as: 'add_to_favorites_service'
  get 'orders/change_order_status', to: 'orders#change_order_status', as: 'change_order_status'

  devise_scope :client do
    get '/clients/sign_up', to: 'clients/registrations#new'
  end

  devise_scope :employee do
    get '/employees/sign_up', to: 'employees/registrations#new'
  end

  get '/select_registration', to: 'index#select_type', as: :select_registration
  get '/best_employees', to: 'orders#best_employees', as: :best_employees
  get '/best_employees_index', to: 'orders#best_employees_index', as: :best_employees_index

  get '/not_approved_orders', to: 'orders#not_approved_orders', as: :not_approved_orders
  get '/approved_orders', to: 'orders#approved_orders', as: :approved_orders
  get '/in_progress_orders', to: 'orders#in_progress_orders', as: :in_progress_orders
  get '/done_orders', to: 'orders#done_orders', as: :done_orders

  get '/orders_sorted_by_date', to: 'orders#orders_sorted_by_date', as: :orders_sorted_by_date
  get '/orders_sorted_by_comments', to: 'orders#orders_sorted_by_comments_quantity', as: :orders_sorted_by_comments
  get '/orders_sorted_by_services', to: 'orders#orders_sorted_by_services', as: :orders_sorted_by_services
  get '/orders_sorted_by_rating', to: 'orders#orders_sorted_by_rating', as: :orders_sorted_by_rating

  get '/exchange', to: 'index#exchange', as: :exchange

  get '/not_approved_orders', to: 'orders#not_approved_orders', as: :not_approved_orders
  get '/approved_orders', to: 'orders#approved_orders', as: :approved_orders
  get '/in_progress_orders', to: 'orders#in_progress_orders', as: :in_progress_orders
  get '/done_orders', to: 'orders#done_orders', as: :done_orders

  get '/services/by_type/:service_type/:rand', to: 'services#by_type', as: 'services_by_type'

  root to: "index#home"
  resources :client_likes
  resources :orders
  resources :services
  resources :client_profiles
  resources :employee_profiles
  resources :comments
  resources :urgencies
  resources :statuses
  resources :specializations
  resources :difficulties
  resources :addresses

  get 'search', to: "services#search"

  get 'calendar', to: "client_profiles#calendar", as: 'calendar'
  get 'employee_calendar', to: "employee_profiles#calendar", as: 'employee_calendar'
  get 'exchange', to: 'index#exchange', as: :exchange
  # get '/change_locale/:lang', to: 'application#change_locale', as: 'change_locale'
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :difficulty
  belongs_to :employee_profile, optional: true

  has_many :client_likes
  has_many :client_profiles, through: :client_likes
  validates :title, uniqueness: { scope: :service_type, message: 'Should be unique for each service type' }

  def self.ransackable_associations(auth_object = nil)
    ["client_likes", "client_profiles", "difficulty", "employee_profile"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "difficulty_id", "employee_profile_id", "id", "id_value", "service_type", "title", "updated_at"]
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[show edit update destroy]

  require 'yaml'
  # GET /services or /services.json
  def index
    @services = Service.all
  end

  # GET /services/1 or /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
    if params[:current_employee_id].present?
      @current_employee = Employee.find(params[:current_employee_id])
      puts "Current employee ID: #{@current_employee.id}"
      @service.employee_profile_id = @current_employee.id
    end
    puts "Service attributes: #{@service.attributes}"
  end

  # GET /services/1/edit
  def edit
  end

  def search
    if params[:q].present?
      search_term = params[:q]

      if I18n.locale == :uk
        services_file = "config/locales/uk.yml"
        result = find_matching_services(search_term, services_file)
        result_keys = result.keys.map(&:parameterize).map(&:underscore)
        @services = Service.all.select do |service|
          result_keys.include?(service.title.parameterize.underscore)
        end
      else
        @services = Service.where("title LIKE ?", "%" + search_term + "%")
      end
    else
      @services = []
    end
  end

  def find_matching_services(search_term, services_file)
    services_data = YAML.load_file(services_file)
    services_titles = services_data["uk"]["index"]["home"]["services_titles"]

    matching_services = {}

    services_titles.each do |key, value|
      matching_services[key] = value if value.downcase.include?(search_term.downcase)
    end

    matching_services
  end

  def by_type
    service_type = params[:service_type]
    @services = Service.where(service_type:).pluck(:id, :title)
    render json: @services
  end

  # POST /services or /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to service_url(@service), notice: "Service was successfully created." }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1 or /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to service_url(@service), notice: "Service was successfully updated." }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1 or /services/1.json
  def destroy
    @service.destroy!

    respond_to do |format|
      format.html { redirect_to services_url, notice: "Service was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_service
    @service = Service.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def service_params
    params.require(:service).permit(:title, :service_type, :difficulty_id, :employee_profile_id, :description)
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_with(model: service) do |form| %>
  <% if service.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>
      
      <ul>
        <% service.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mt">
    <%= form.label :title, t('services_data.service_name'), style: "display: block" %>
    <%= form.text_field :title, class: 'form-text-field'  %>
  </div>

  <div class="field mt">
    <%= form.label :service_type, t('services_data.service_type_name'), style: "display: block" %>
    <%= form.text_field :service_type, class: 'form-text-field'  %>
  </div>

  <div class="field mt">
    <%= form.label :difficulty_id, t("services_data.service.difficulty"), style: "display: block" %>
    <% options = Difficulty.all.map { |d| [I18n.exists?("difficulty.difficulty_titles.#{d.title.parameterize.underscore}", locale: :uk) ? t("difficulty.difficulty_titles.#{d.title.parameterize.underscore}") : d.title, d.id] } %>
    <%= form.select :difficulty_id, options_for_select(options, prompt: 'Select difficulty'), {}, class: 'form-text-field', style: "width: 300px;" %>
  </div>

  <div class="field mt">
    <%= form.label :description, t('services_data.service.description'), style: "display: block" %>
    <%= form.text_area :description, class: 'form-text-area'  %>
  </div>

  <%= form.hidden_field :employee_profile_id, value:current_employee.id %>

  <div class="field mt">
    <%= form.submit t('save'), class: 'button button-main' %>
  </div>
<% end %>

app/views/services/_service.html.erb
<div id="<%= dom_id service %>">
  <div class="mt-md">
    <strong><%= t('services_data.service.title') %>:</strong>
    <% if I18n.locale == :uk %>
      <%= I18n.t("index.home.services_titles.#{service.title.parameterize.underscore}") %>
    <% else %>
      <%= service.title %>
    <% end %>
  </div>

  <div class="mt-sm mb-sm">
    <strong><%= t('services_data.service_type_name') %>:</strong>
    <% if I18n.locale == :uk %>
      <%= I18n.t("index.home.services_types.#{service.service_type.parameterize.underscore}") %>
    <% else %>
      <%= service.service_type %>
    <% end %>
  </div>

  <% if @service.present? && @service.difficulty.present? %>
  <div class="mt-sm mb-sm">
    <strong><%= t('services_data.service.difficulty') %>:</strong>
    <% if I18n.locale == :uk %>
      <%= I18n.t("difficulty.difficulty_titles.#{@service.difficulty.title.parameterize.underscore}") %>
    <% else %>
      <%= @service.difficulty.title %>
    <% end %>
  </div>

  <div class="mt-sm mb-sm">
    <strong><%= t('services_data.service.who_created') %>:</strong>
    <% if service.employee_profile_id.present? %>
      <%= EmployeeProfile.find_by(id: service.employee_profile_id).last_name %>
    <% else %>
      Admin
    <% end %>
  </div>

  <div class="mt-sm mb-sm">
    <strong><%= t('services_data.service.description') %>:</strong>
    <div class="mt-sm" style="width: 600px; height: 200px; overflow-x: auto; overflow-y: auto;">
      <%= @service.description %>
    </div>
  </div>

<% end %>

</div>

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render "form", service: @service %>

<br>

<div>
  <%= link_to "Show this service", @service %> |
  <%= link_to "Back to services", services_path %>
</div>

app/views/services/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Services</h1>

<div id="services">
  <% @services.each do |service| %>
     <%= render service %>

    <p>
      <%= link_to "Show this service", service %>
    </p>
  <% end %>
</div>

<%= link_to "New service", new_service_path %>

app/views/services/new.html.erb
<div class="container">
  <h2 class="title-lg mb"><%= t('services_data.new.title') %></h2>
  <%= render "form", service: @service %>
  <br>
  <div>
    <%= link_to t("back_to_main"), root_path, class: 'button button-yellow'%>
  </div>
</div>

app/views/services/search.html.erb
<div class="container">
  <h2 class="title-lg mb"><%= t('services') %></h2>
  <p style="color: green"><%= notice %></p>

  <% @services.each_with_index do |service, index| %>
    <br>
    <div class="user-card mt-ls">
      <%= render service %>
    </div>
    
    <div class="mt-md ml-bt">  
      <%= link_to t('show_more'), service_path(service.id), class: 'button button-main' %>
    </div>

  <% end %>
  
  <br>
  <div class="field mt-ls">
    <%= link_to t('back_to_main'), root_path, class: 'button button-yellow' %>
  </div>
</div>

app/views/services/show.html.erb
<div class="container">
  <% if notice.present? %>
    <p class="mb-ls" style="color: green"><%= notice %></p>
  <% end %>

  <% if alert.present? %>
    <p class="mb-ls" style="color: red"><%= alert %></p>
  <% end %>

  <h2 class="title-lg mb"><%= t('services_data.service_name') %></h2>

  <%= render @service %>
  
    <div class="field mt">
      <% if client_signed_in? %>
        <%= link_to t('add_to_fav'), add_to_favorites_service_path(service_id: @service.id, client_profile_id: current_client.id), method: :post, class: 'button button-yellow'  %>
      <% end %>
      <%= link_to t('back_to_main'), root_path, class: 'button button-yellow' %>
    </div>
</div>