config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :clients, controllers: { registrations: 'clients/registrations', sessions: 'clients/sessions' }
  devise_for :employees, controllers: { registrations: 'employees/registrations', sessions: 'employees/sessions' }

  get 'services/:id/add_to_favorites', to: 'client_profiles#add_to_favorites', as: 'add_to_favorites_service'
  get 'orders/change_order_status', to: 'orders#change_order_status', as: 'change_order_status'

  devise_scope :client do
    get '/clients/sign_up', to: 'clients/registrations#new'
  end

  devise_scope :employee do
    get '/employees/sign_up', to: 'employees/registrations#new'
  end

  get '/select_registration', to: 'index#select_type', as: :select_registration
  get '/best_employees', to: 'orders#best_employees', as: :best_employees
  get '/best_employees_index', to: 'orders#best_employees_index', as: :best_employees_index

  get '/not_approved_orders', to: 'orders#not_approved_orders', as: :not_approved_orders
  get '/approved_orders', to: 'orders#approved_orders', as: :approved_orders
  get '/in_progress_orders', to: 'orders#in_progress_orders', as: :in_progress_orders
  get '/done_orders', to: 'orders#done_orders', as: :done_orders

  get '/orders_sorted_by_date', to: 'orders#orders_sorted_by_date', as: :orders_sorted_by_date
  get '/orders_sorted_by_comments', to: 'orders#orders_sorted_by_comments_quantity', as: :orders_sorted_by_comments
  get '/orders_sorted_by_services', to: 'orders#orders_sorted_by_services', as: :orders_sorted_by_services
  get '/orders_sorted_by_rating', to: 'orders#orders_sorted_by_rating', as: :orders_sorted_by_rating

  get '/exchange', to: 'index#exchange', as: :exchange

  get '/not_approved_orders', to: 'orders#not_approved_orders', as: :not_approved_orders
  get '/approved_orders', to: 'orders#approved_orders', as: :approved_orders
  get '/in_progress_orders', to: 'orders#in_progress_orders', as: :in_progress_orders
  get '/done_orders', to: 'orders#done_orders', as: :done_orders

  get '/services/by_type/:service_type/:rand', to: 'services#by_type', as: 'services_by_type'

  root to: "index#home"
  resources :client_likes
  resources :orders
  resources :services
  resources :client_profiles
  resources :employee_profiles
  resources :comments
  resources :urgencies
  resources :statuses
  resources :specializations
  resources :difficulties
  resources :addresses

  get 'search', to: "services#search"

  get 'calendar', to: "client_profiles#calendar", as: 'calendar'
  get 'employee_calendar', to: "employee_profiles#calendar", as: 'employee_calendar'
  get 'exchange', to: 'index#exchange', as: :exchange
  # get '/change_locale/:lang', to: 'application#change_locale', as: 'change_locale'
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/client_like.rb
class ClientLike < ApplicationRecord
  belongs_to :client_profile
  belongs_to :service

  def self.ransackable_attributes(auth_object = nil)
    ["client_profile_id", "created_at", "id", "id_value", "service_id", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["client_profile", "service"]
  end
end

app/controllers/client_likes_controller.rb
class ClientLikesController < ApplicationController
  before_action :set_client_like, only: %i[show edit update destroy]

  # GET /client_likes or /client_likes.json
  def index
    # @client_likes = ClientLike.all
    @client_likes = ClientLike.joins(:service).order('services.title')
  end

  # GET /client_likes/1 or /client_likes/1.json
  def show
  end

  # GET /client_likes/new
  def new
    @client_like = ClientLike.new
  end

  # GET /client_likes/1/edit
  def edit
  end

  # POST /client_likes or /client_likes.json
  def create
    @client_like = ClientLike.new(client_like_params)

    respond_to do |format|
      if @client_like.save
        format.html { redirect_to client_like_url(@client_like), notice: "Client like was successfully created." }
        format.json { render :show, status: :created, location: @client_like }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client_like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /client_likes/1 or /client_likes/1.json
  def update
    respond_to do |format|
      if @client_like.update(client_like_params)
        format.html { redirect_to client_like_url(@client_like), notice: "Client like was successfully updated." }
        format.json { render :show, status: :ok, location: @client_like }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client_like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /client_likes/1 or /client_likes/1.json
  def destroy
    @client_like.destroy!

    respond_to do |format|
      format.html { redirect_to client_likes_url, notice: "Client like was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_client_like
    @client_like = ClientLike.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def client_like_params
    params.require(:client_like).permit(:client_profile_id, :service_id)
  end
end

app/helpers/client_likes_helper.rb
module ClientLikesHelper
end

app/views/client_likes/_client_like.html.erb
<div id="<%= dom_id client_like %>">

  <% service = Service.find_by(id: client_like.service_id) %>
  <p>
    <strong><%= t('services.service_name') %>:</strong>
    <% if I18n.locale == :uk %>
      <%= I18n.t("index.home.services_titles.#{service.title.parameterize.underscore}") %>
    <% else %>
      <%= service.title %>
    <% end %>
  </p>

  <p>
    <strong><%= t('services.service_type_name') %>:</strong>    
    <% if I18n.locale == :uk %>
      <%= I18n.t("index.home.services_types.#{service.service_type.parameterize.underscore}") %>
    <% else %>
      <%= service.service_type %>
    <% end %>
  </p>
</div>

app/views/client_likes/_form.html.erb
<%= form_with(model: client_like) do |form| %>
  <% if client_like.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client_like.errors.count, "error") %> prohibited this client_like from being saved:</h2>

      <ul>
        <% client_like.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :client_profile_id, style: "display: block" %>
    <%= form.text_field :client_profile_id %>
  </div>

  <div>
    <%= form.label :service_id, style: "display: block" %>
    <%= form.text_field :service_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/client_likes/edit.html.erb
<h1>Editing client like</h1>

<%= render "form", client_like: @client_like %>

<br>

<div>
  <%= link_to "Show this client like", @client_like %> |
  <%= link_to "Back to client likes", client_likes_path %>
</div>

app/views/client_likes/index.html.erb
<div class="container">
  <% if notice.present? %>
    <p class="mb-ls" style="color: green"><%= notice %></p>
  <% end %>

  <% if alert.present? %>
    <p class="mb-ls" style="color: red"><%= alert %></p>
  <% end %>

  <h2 class="title-lg mb"><%= t('.title') %></h2>

  <% if @client_likes.any? { |client_like| client_like.client_profile_id == current_client.id } %>
    <% @client_likes.each do |client_like| %>
      <% if client_like.client_profile_id == current_client.id %>
        <br>
        <div class="user-card mt-ls">
          <%= render client_like %>
        </div>
        
        <div class="mt-md ml-bt">  
          <%= link_to t('show_more'), service_path(client_like.service_id), class: 'button button-main' %>
          <%= button_to t('delete'), client_like, method: :delete, data: { confirm: "Are you sure you want to delete this client_like?" }, class: 'button button-main' %>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <p style="color: red; font-weight: bold;"><%= t('.absence_message') %></p>
  <% end %>  


  
    <div class="field mt-ls">
      <%= link_to t('show_profile'), client_profile_path(current_client), class: 'button button-yellow' %>
      <%= link_to t('back_to_main'), root_path, class: 'button button-yellow' %> <br />
    </div>
</div>

app/views/client_likes/new.html.erb
<h1>New client like</h1>

<%= render "form", client_like: @client_like %>

<br>

<div>
  <%= link_to "Back to client likes", client_likes_path %>
</div>

app/views/client_likes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client_like %>

<div>
  <%= link_to "Edit this client like", edit_client_like_path(@client_like) %> |
  <%= link_to "Back to client likes", client_likes_path %>

  <%= button_to "Destroy this client like", @client_like, method: :delete %>
</div>