config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :clients, controllers: { registrations: 'clients/registrations', sessions: 'clients/sessions' }
  devise_for :employees, controllers: { registrations: 'employees/registrations', sessions: 'employees/sessions' }

  get 'services/:id/add_to_favorites', to: 'client_profiles#add_to_favorites', as: 'add_to_favorites_service'
  get 'orders/change_order_status', to: 'orders#change_order_status', as: 'change_order_status'

  devise_scope :client do
    get '/clients/sign_up', to: 'clients/registrations#new'
  end

  devise_scope :employee do
    get '/employees/sign_up', to: 'employees/registrations#new'
  end

  get '/select_registration', to: 'index#select_type', as: :select_registration
  get '/best_employees', to: 'orders#best_employees', as: :best_employees
  get '/best_employees_index', to: 'orders#best_employees_index', as: :best_employees_index

  get '/not_approved_orders', to: 'orders#not_approved_orders', as: :not_approved_orders
  get '/approved_orders', to: 'orders#approved_orders', as: :approved_orders
  get '/in_progress_orders', to: 'orders#in_progress_orders', as: :in_progress_orders
  get '/done_orders', to: 'orders#done_orders', as: :done_orders

  get '/orders_sorted_by_date', to: 'orders#orders_sorted_by_date', as: :orders_sorted_by_date
  get '/orders_sorted_by_comments', to: 'orders#orders_sorted_by_comments_quantity', as: :orders_sorted_by_comments
  get '/orders_sorted_by_services', to: 'orders#orders_sorted_by_services', as: :orders_sorted_by_services
  get '/orders_sorted_by_rating', to: 'orders#orders_sorted_by_rating', as: :orders_sorted_by_rating

  get '/exchange', to: 'index#exchange', as: :exchange

  get '/not_approved_orders', to: 'orders#not_approved_orders', as: :not_approved_orders
  get '/approved_orders', to: 'orders#approved_orders', as: :approved_orders
  get '/in_progress_orders', to: 'orders#in_progress_orders', as: :in_progress_orders
  get '/done_orders', to: 'orders#done_orders', as: :done_orders

  get '/services/by_type/:service_type/:rand', to: 'services#by_type', as: 'services_by_type'

  root to: "index#home"
  resources :client_likes
  resources :orders
  resources :services
  resources :client_profiles
  resources :employee_profiles
  resources :comments
  resources :urgencies
  resources :statuses
  resources :specializations
  resources :difficulties
  resources :addresses

  get 'search', to: "services#search"

  get 'calendar', to: "client_profiles#calendar", as: 'calendar'
  get 'employee_calendar', to: "employee_profiles#calendar", as: 'employee_calendar'
  get 'exchange', to: 'index#exchange', as: :exchange
  # get '/change_locale/:lang', to: 'application#change_locale', as: 'change_locale'
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/index/exchange.html.erb
<html lang="en">
<head>
  <link rel="stylesheet" href="css/style.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <style>
    .exchange-rates {
      font-family: Arial, sans-serif;
      border: 1px solid #ccc;
      padding: 10px;
      border-radius: 5px;
      margin: 20px 0;
    }

    .exchange-rates h2 {
      font-size: 20px;
      margin-bottom: 10px;
    }

    .exchange-rates ul {
      list-style-type: none;
      padding: 0;
      margin: 0;
    }

    .exchange-rates li {
      margin-bottom: 5px;
    }

    .exchange-rates li span {
      font-weight: bold;
    }
  </style>

</head>
<body>
    <div class="container">
        <p class="title-md"style="color: green"><%= notice %></p>

      <div class="exchange-rates">
        <h2><%= t('exchange_rates.title') %></h2>
        <ul>
          <% @exchange_rates.each do |rate| %>
            <li><span><%= t("exchange_rates.ccy.#{rate['ccy']}") %></span> <%= t('exchange_rates.to_UAH') %>: <span><%= sprintf('%.2f', rate['buy']) %></span> (<%= t('exchange_rates.buy') %>), <span><%= sprintf('%.2f', rate['sale']) %></span> (<%= t('exchange_rates.sale') %>)</li>
          <% end %>
        </ul>
      </div>

      <%= link_to t('back_to_main'), root_path, class: 'button button-yellow' %>

    </div>
</body>
</html>

app/views/index/home.html.erb
<html lang="en">
<head>
  <link rel="stylesheet" href="css/style.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div class="container">
        <p class="title-md"style="color: green"><%= notice %></p>

        <div class="mt-md mb-ls">
            <% if client_signed_in? %>
                <%= link_to t(".best"), best_employees_path, class: 'button button-yellow'%>
            <% end %>
        </div>

        <h1><%= t(".services_header") %></h1>
        <div class="grid-container">
        <% @services_by_type.each do |service_type, services| %>
            <div class="service-type-container">
            <% if I18n.locale == :uk %>
                <% type_key = "index.home.services_types.#{service_type.parameterize.underscore}" %>
                <% if I18n.exists?(type_key, locale: :uk) %>
                    <h2 class="grid-item"><%= t(type_key) %></h2>
                <% else %>
                    <h2 class="grid-item"><%= service_type %></h2>
                <% end %>
            <% else %>
                <h2 class="grid-item"><%= service_type %></h2>
            <% end %>
            <ul class="service-list">
                <% services.each do |service| %>
                <% key = "index.home.services_titles.#{service.title.parameterize.underscore}" %>
                <% if I18n.exists?(key, locale: :uk) %>
                    <li><%= link_to t(key), service_path(service) %></li>
                <% else %>
                    <li><%= link_to service.title, service_path(service) %></li>
                <% end %>
                <% end %>
            </ul>
            </div>
        <% end %>
        </div>

        <footer class="footer">
            <div class="row">
                <div class="footer-col">
                    <h4><%= t(".footer.about_us") %></h4>
                    <ul>
                        <% t('.footer.about_us_list').each do |key, value| %>
                            <li><%= link_to t(".footer.about_us_list.#{key}"), '#' %></li>
                        <% end %>
                  </ul>
                </div>
                <div class="footer-col">
                    <h4><%= t(".footer.how_it_works") %></h4>
                    <ul>
                        <% t('.footer.how_it_works_list').each do |key, value| %>
                            <li><%= link_to t(".footer.how_it_works_list.#{key}"), '#' %></li>
                        <% end %>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4><%= t(".footer.help") %></h4>
                    <ul>
                        <% t('.footer.help_list').each do |key, value| %>
                            <li><%= link_to t(".footer.help_list.#{key}"), '#' %></li>
                        <% end %>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4><%= t(".footer.follow") %></h4>
                    <div class="social-links">
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                        <a href="#"><i class="fab fa-youtube"></i></a>
                    </div>
                </div>
            </div>
        </footer>

    </div>

</body>
</html>

app/views/index/select_type.html.erb
<div class="container">
  <h2 class="title-lg mb"><%= t("choose-option")%></h2>
  <div class="mt-md">
    <%= link_to "#{t("sign-up-cli")}", new_client_registration_path, class: 'button button-yellow large  mr-sm' %>
  </div>
  <div class="mt-md">
    <%= link_to "#{t("sign-up-emp")}", new_employee_registration_path, class: 'button button-yellow large mr-sm' %>
  </div>
</div>